---
RecipeFormatVersion: "2020-01-25"
ComponentName: software.amazon.awssdk.sdk-gg-ipc
ComponentVersion: "1.0.0"
ComponentDescription: "This is test for the Greengrass IPC sample"
ComponentPublisher: "iot-device-sdk"
ComponentConfiguration:
  DefaultConfiguration:
    accessControl:
      aws.greengrass.ipc.mqttproxy:
        software.amazon.awssdk.sdk-gg-ipc:mqttproxy:1:
          policyDescription: "Allows access to publish and subscribe to a Greengrass IPC test topic"
          operations:
            - aws.greengrass#PublishToIoTCore
            - aws.greengrass#SubscribeToIoTCore
          resources:
            - "test/gg-ipc-topic"
    Message: "World"
Manifests:
  - Platform:
      os: all
    Artifacts:
      - URI: "file:greengrass-ipc"
        Permission:
          Read: ALL
          Execute: ALL
    Lifecycle:
      Run: |
        {artifacts:path}/greengrass-ipc --topic test/gg-ipc-topic --message hello --is_ci
