#pragma once

/* Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0.
 *
 * This file is generated
 */

#include <aws/crt/DateTime.h>
#include <aws/iotcommand/RejectedErrorCode.h>

#include <aws/iotcommand/Exports.h>

#include <aws/crt/JsonObject.h>
#include <aws/crt/StlAllocator.h>

namespace Aws
{
    namespace Iotcommand
    {

        /**
         * Response document containing details about a failed request.
         *
         */
        class AWS_IOTCOMMAND_API V2ServiceError final
        {
          public:
            V2ServiceError() = default;

            V2ServiceError(const Crt::JsonView &doc);
            V2ServiceError &operator=(const Crt::JsonView &doc);

            void SerializeToObject(Crt::JsonObject &doc) const;

            /**
             * Indicates the type of error.
             *
             */
            Aws::Crt::Optional<Aws::Iotcommand::RejectedErrorCode> Code;

            /**
             * A text message that provides additional information.
             *
             */
            Aws::Crt::Optional<Aws::Crt::String> Message;

            /**
             * The date and time the response was generated by AWS IoT.
             *
             */
            Aws::Crt::Optional<Aws::Crt::DateTime> Timestamp;

          private:
            static void LoadFromObject(V2ServiceError &obj, const Crt::JsonView &doc);
        };
    } // namespace Iotcommand
} // namespace Aws
