name: Lint

on:
  push:
    branches-ignore:
      - 'main'
      - 'docs'

jobs:
  clang-format:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Sources
      uses: actions/checkout@v1

    - name: clang-format lint
      uses: DoozyX/clang-format-lint-action@v0.3.1
      with:
        # List of extensions to check
        extensions: cpp,h
        inplace: True
    - uses: EndBug/add-and-commit@v4
      with:
        author_name: xiazhvera
        author_email: zhvxia@amazon.com
        message: 'Committing clang-format changes'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
