name: Release

env:
  GH_TOKEN: ${{ github.token }}

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: "Release type:"
        required: true
        options:
          - bug fix (PATCH)
          - new feature (MINOR)
      release_title:
        description: "The title of the release"
        required: true

jobs:
  update-version:
    runs-on: ubuntu-20.04 # latest
    permissions:
      contents: write # allow push
      pull-requests: write # allow making PR

    steps:
    - name: Checkout Sources
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Make new release
      env:
        Title: ${{ github.event.inputs.release_title }}
      run: |
        # Escape special characters
        Title=$(echo ${Title//[\"]\\\"})
        Title=$(echo ${Title//[\']\\\'})
        Title=$(echo ${Title//[\$]})

        ./utils/publish-release.sh "${{ github.event.inputs.release_type }}" "$Title"
