name: Release

env:
  GH_TOKEN: ${{ github.token }}

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: "The type of release to make (Minor, Patch, etc)"
        required: true
        options:
          - PATCH
          - MINOR
      release_title:
        description: "The title of the release"
        required: true

jobs:
  update-version:
    runs-on: ubuntu-20.04 # latest
    permissions:
      contents: write # allow push

    steps:
    - name: Checkout Sources
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Make new release
      run: |
        ./publish-release.sh "${{ github.event.inputs.release_type }}" "${{ github.event.inputs.release_title }}"
